//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesHUB
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int o_id { get; set; }
        public System.DateTime o_date { get; set; }
        public int p_id { get; set; }
        public string u_name { get; set; }
        public string u_email { get; set; }
        public string u_phone { get; set; }
        public string u_address { get; set; }
        public Nullable<int> o_payment { get; set; }
        public string o_paymentStatus { get; set; }
        public string o_deliveryStatus { get; set; }
        public Nullable<int> p_quantity { get; set; }
    }
}
