//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesHUB
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int p_id { get; set; }
        public string p_name { get; set; }
        public int p_price { get; set; }
        public int c_id { get; set; }
        public string p_desc { get; set; }
        public string p_keywords { get; set; }
        public byte[] p_img1 { get; set; }
        public byte[] p_img2 { get; set; }
        public int region { get; set; }
    }
}
